#!/bin/sh

DIR=$HOME
if [ "$DIR" = "/" ]; then 
    echo "Switching to tmp" 
    DIR="/tmp"
else
    DIR="$DIR/.cache"
fi;

mkdir -p $DIR
cd $DIR
if [ -e newm_log_bu1 ]
    then cp newm_log_bu1 newm_log_bu2
fi
if [ -e newm_log ]
    then cp newm_log newm_log_bu1
fi
cd $HOME

debug="False"
if [ "$1" = "-d" ]; then
    debug="True"
fi

exec python -u -c "from newm import run; run($debug)" > $DIR/newm_log 2>&1
