#+TITLE: newm developer information

* Current (v0.2)
** Multi-output support
*** STRT Multi-output
- [ ] Backgrounds when moving window between workspaces (issue with move_origin)
- [ ] Improved background (probably more general issue)
- [ ] Open second screen, overview -> Hacky background animation (sth to do with scaling and pywm.round)
- [ ] Occasionally slow animations when having a second virtual output
- [ ] Move between screens: Shortcuts

*** DONE Exec config for commands to be run after startup

*** TODO Bugs
- [ ] If width is not divisible by 3, 3x3 grid produces a lot of "Potential scaling issue"... Only false positive? In that case optimize the warning
- [ ] Transitioning from overview to fullscreen does not work
- [ ] Scaling a window to the left means right border jumps, to the right is ok

*** TODO Release
- [ ] TODO comments
- [ ] Document newm-cmd open/close-virtual-output - link to newm-sidecar
- [ ] Document new config options


* v0.3
** Scale windows moving others "out of the way"
** Improved panel
- Useful handling of multiple workspaces
- Bars as panels not as widgets
- layer-shell for bars and possibly more?
- Possibly flutter-based?
- Drop websockets and with that newm-panel-nwjs but keep newm_panel_basic
*** TODO Specify requirements for newm <-> panel interaction

* Backlog / Ideas
** Dynamic background?
** Titles during OverviewOverlay
** Allow certain overlays to start during animations (e.g. 3/4-Finger-Swipe during animation one view)
** Autoplace the first couple of windows more like i3 (i.e. resizing existing windows / tiling)


* Setup clean arch chroot / qemu for testing

** Setup chroot

Following https://www.collabora.com/news-and-blog/blog/2019/03/20/bootstraping-a-minimal-arch-linux-image/

#+BEGIN_SRC sh
truncate -s 20G arch_disk.raw
mkfs.ext4 arch_disk.raw
mkdir mnt
sudo mount arch_disk.raw mnt
sudo pacstrap mnt base base-devel linux linux-firmware
sudo arch-chroot mnt
#+END_SRC

Now we are inside the chroot, very basic setup:

#+BEGIN_SRC sh
passwd
pacman -S dhcpcd

useradd --create-home test
passwd test
usermod -aG wheel test
vim /etc/sudoers # add wheel
su test
#+END_SRC

Finally clean up

#+BEGIN_SRC sh
exit
sudo umount mnt
#+END_SRC

** VSetup virtual machine

To use the disk in a virtual machine (not incredibly nice...)

#+BEGIN_SRC sh
sudo mount arch_disk.raw mnt
cp -r mnt/boot mnt_boot
sudo umount mnt
#+END_SRC

and start using

#+BEGIN_SRC sh
qemu-system-x86_64 --enable-kvm -hda arch_disk.raw -m 4G -kernel mnt_boot/vmlinuz-linux -initrd mnt_boot/initramfs-linux[-fallback].img -append "root=/dev/sda rw" -vga virtio
#+END_SRC

To enable internet access, probably

#+BEGIN_SRC sh
systemctl enable dhcpcd
systemctl start dhcpcd
#+END_SRC

is necessary
